development:
  adapter: postgresql
  encoding: utf8
  database: sample_app_development
  username: algirdas
  password: neatspesi
  template: template0 # Required for UTF8 encoding
 
test:
  adapter: postgresql
  encoding: utf8
  database: sample_app_test
  username: algirdas
  password: neatspesi
  template: template0 # Required for UTF8 encoding
 
production:
  adapter: postgresql
  encoding: utf8
  database: sample_app_production
  username: algirdas
  password: neatspesi
  template: template0 # Required for UTF8 encoding